/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class Defaulters extends javax.swing.JFrame {

    /**
     * Creates new form issuebookdetails
     */DefaultTableModel model;
    public Defaulters() {
        initComponents();
        setuserDetailstotable();
    }
     public void setuserDetailstotable(){
         long currentTime = System.currentTimeMillis();
        Date todaysDate = new Date(currentTime);
        java.sql.Date sqlDate = new java.sql.Date(todaysDate.getTime());
              
        
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/libsa","root","");
             PreparedStatement pst =con.prepareStatement("SELECT * FROM `issue_books` WHERE due_date < ? and status = ?");
             pst.setDate(1,sqlDate);
             pst.setString(2, "pending");
            ResultSet rs = pst.executeQuery();

            while (rs.next()){
                String issue_id=rs.getString("issue_id");
                String bookname=rs.getString("bookname");
                String username=rs.getString("username");
                String issuedate=rs.getString("issue_date");
                String duedate=rs.getString("due_date");
                String status=rs.getString("status");
                
                Object[] obj={ issue_id,bookname,username,issuedate,duedate,status   
                };
                model =(DefaultTableModel) tbl_records.getModel();
                model.addRow(obj);
            }
        }catch (Exception e){
            e.printStackTrace();
            
        }
        
    }
     private double calculateFine(String dueDate) {
    try {
        // Parse the due date from String to java.sql.Date
        java.sql.Date sqlDueDate = java.sql.Date.valueOf(dueDate);

        // Get the current date
        long currentTime = System.currentTimeMillis();
        java.sql.Date currentDate = new java.sql.Date(currentTime);

        // Calculate the difference in milliseconds and days
        long diffInMillies = sqlDueDate.getTime() - currentDate.getTime();
        long diffInDays = diffInMillies / (24 * 60 * 60 * 1000);

        // Check if the due date is after the current date
        if (diffInDays > 0) {
            // The book is not overdue, return 0 fine
            return 0.0;
        }

        // Assume a fine rate of 20 sh per day
        double fineRate = 20.0;

        // Calculate the fine (make sure it's positive)
        double fine = Math.abs(fineRate * diffInDays);

        return fine;
    } catch (Exception e) {
        e.printStackTrace();
        return 0.0; // Return 0 if there's an error
    }
}
     private void displayReceipt(String issue_id, String bookname, String username, String issuedate, String duedate, String status, double fine) {
    // Implement the logic to display the receipt
    // You can use JOptionPane.showMessageDialog or create a new JFrame to display the receipt
    // Customize the receipt format based on your requirements

    StringBuilder receipt = new StringBuilder();
    receipt.append("Receipt\n");
    receipt.append("----------------------------\n");
    receipt.append("Issue ID: ").append(issue_id).append("\n");
    receipt.append("Book Name: ").append(bookname).append("\n");
    receipt.append("Username: ").append(username).append("\n");
    receipt.append("Issue Date: ").append(issuedate).append("\n");
    receipt.append("Due Date: ").append(duedate).append("\n");
    receipt.append("Status: ").append(status).append("\n");

    if (fine > 0.0) {
        receipt.append("Fine: ").append(fine).append(" sh").append("\n");
    } else {
        receipt.append("Fine: None\n"); // No fine if it's not overdue
    }

    receipt.append("----------------------------\n");

    JOptionPane.showMessageDialog(this, receipt.toString(), "Fine Receipt", JOptionPane.INFORMATION_MESSAGE);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_records = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 330, 4));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Edit_Property_50px.png"))); // NOI18N
        jLabel2.setText("Defaulters");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 320, 60));

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel13.setText("Back");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 60, 40));

        tbl_records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "issue_Id", "Bookname", "Username", "Issuedate", "Duedate", "Status"
            }
        ));
        tbl_records.setColorBackgoundHead(new java.awt.Color(255, 153, 0));
        tbl_records.setColorBordeHead(new java.awt.Color(102, 0, 102));
        tbl_records.setRowHeight(30);
        tbl_records.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_recordsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_records);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 900, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 930, 540));

        setSize(new java.awt.Dimension(955, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void tbl_recordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_recordsMouseClicked

        int selectedRow = tbl_records.getSelectedRow();
    if (selectedRow != -1) {
        // Get the necessary information from the selected row
        String issue_id = model.getValueAt(selectedRow, 0).toString();
        String bookname = model.getValueAt(selectedRow, 1).toString();
        String username = model.getValueAt(selectedRow, 2).toString();
        String issuedate = model.getValueAt(selectedRow, 3).toString();
        String duedate = model.getValueAt(selectedRow, 4).toString();
        String status = model.getValueAt(selectedRow, 5).toString();

        // Calculate the fine based on the due date and current date
        double fine = calculateFine(duedate);

        // Display the receipt
        displayReceipt(issue_id, bookname, username, issuedate, duedate, status, fine);
    }
    }//GEN-LAST:event_tbl_recordsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Defaulters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Defaulters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Defaulters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Defaulters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Defaulters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSTableMetro tbl_records;
    // End of variables declaration//GEN-END:variables
}
