/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;


/**
 *
 * @author pc
 */
public class mybooks extends javax.swing.JFrame {
    private String bookTitle;
    private String bookAuthor;
    private int duration;
    private Connection connection;
   
    
    public mybooks() {
        initComponents();
        tblbooks = new JTable(); // Initialize tblbooks
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Title");
        model.addColumn("Author");
        model.addColumn("Duration");
        tblbooks.setModel(model);
        try {
        connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/libsa", "root", "");
    } catch (SQLException e) {
        e.printStackTrace();
    }
        populateTableFromDatabase();
       
    }
    public void addBookToDatabase(String bookTitle, String bookAuthor, int duration) {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/libsa", "root", "");
            PreparedStatement stmt = con.prepareStatement("INSERT INTO mybooks (title, author, duration) VALUES (?, ?, ?)");
            stmt.setString(1, bookTitle);
            stmt.setString(2, bookAuthor);
            stmt.setInt(3, duration);
            stmt.executeUpdate();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    // Method to retrieve books from the database and populate the table
    public void populateTableFromDatabase() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/libsa", "root", "");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM mybooks");
            DefaultTableModel model = (DefaultTableModel) tblbooks.getModel();
            while (rs.next()) {
                String title = rs.getString("title");
                String author = rs.getString("author");
                int duration = rs.getInt("duration");
                 Object[] obj = {title, author, duration};
                 
                 model =(DefaultTableModel) tblbooks.getModel();
                 model.addRow(obj);
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    public mybooks(String bookTitle, String bookAuthor, int duration) {
        this();
        this.bookTitle = bookTitle;
        this.bookAuthor = bookAuthor;
        this.duration = duration;
        
        addBook(bookTitle, bookAuthor, duration);
    }
   
    
    public void addBook(String bookTitle, String bookAuthor, int duration) {
    DefaultTableModel model = (DefaultTableModel) tblbooks.getModel();
    model.addRow(new Object[]{bookTitle, bookAuthor, duration});
    model.fireTableDataChanged();
}

    public void setTableModel(DefaultTableModel model) {
        tblbooks.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbooks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MY BOOKS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 36, 218, 58));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        tblbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title ", "Author", "Duration"
            }
        ));
        jScrollPane1.setViewportView(tblbooks);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 740, 320));

        setBounds(0, 0, 838, 483);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mybooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mybooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mybooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mybooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mybooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbooks;
    // End of variables declaration//GEN-END:variables
}
