/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.UUID;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.Calendar;
import static jframes.DBConnection.getConnection;

/**
 *
 * @author pc
 */
public class plan extends javax.swing.JFrame {
    private String username;
    

    /**
     * Creates new form plan
     */
    public plan(String username) {
        this.username = username;
        System.out.println("Username: " + username);
        initComponents();
    }
     
       
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        date2 = new javax.swing.JLabel();
        combosub = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        dates = new rojeru_san.componentes.RSDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnsubmited = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("200ksh");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MONTHLY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 16, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Free Delivery");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 204, 47));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("Borrow up to 5 books");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 204, 47));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 360));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPanel3.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 170, 47));

        combosub.setBackground(new java.awt.Color(255, 102, 0));
        combosub.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        combosub.setForeground(new java.awt.Color(255, 255, 255));
        combosub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Annually", "Monthly" }));
        combosub.setAutoscrolls(true);
        jPanel3.add(combosub, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Subscription type");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 47));

        dates.setColorBackground(new java.awt.Color(255, 102, 0));
        dates.setColorForeground(new java.awt.Color(255, 102, 0));
        jPanel3.add(dates, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 190, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("Start date");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 47));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel13.setText("End date");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 100, 47));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 290, 470));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2100ksh");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ANNUALLY");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 16, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 280, 100));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Free Delivery");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 204, 47));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setText("10% Discount");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 204, 47));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("Borrow up to 5 books");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 204, 47));

        btnsubmited.setBackground(new java.awt.Color(255, 102, 0));
        btnsubmited.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnsubmited.setForeground(new java.awt.Color(255, 255, 255));
        btnsubmited.setText("NEXT");
        btnsubmited.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitedActionPerformed(evt);
            }
        });
        jPanel5.add(btnsubmited, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 140, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 280, 370));

        setSize(new java.awt.Dimension(903, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitedActionPerformed
        // TODO add your handling code here:
        String subscriptionType = (String) combosub.getSelectedItem();
    Date startDate = dates.getDatoFecha();
    Calendar c = Calendar.getInstance();
    c.setTime(startDate);

    if (subscriptionType.equalsIgnoreCase("annually")) {
        c.add(Calendar.YEAR, 1);  // add one year
    } else if (subscriptionType.equalsIgnoreCase("monthly")) {
        c.add(Calendar.MONTH, 1);  // add one month
    }

    Date endDate = c.getTime();
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    String strStartDate = format.format(startDate); 
    String strEndDate = format.format(endDate);
    System.out.println("End Date: " + strEndDate);
    date2.setText(strEndDate);
    
    // Calculate payment amount
    int paymentAmount = 0;
    if (subscriptionType.equalsIgnoreCase("annually")) {
        paymentAmount = 2100; // Annual subscription fee
    } else if (subscriptionType.equalsIgnoreCase("monthly")) {
        paymentAmount = 200; // Monthly subscription fee
    }
    
    // Update the database with subscription details
    try {
        Connection conn = getConnection();
        String query = "INSERT INTO subscriptions (username, start_date, end_date, subscription_type, payment_status) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, this.username);
        pstmt.setString(2, strStartDate);
        pstmt.setString(3, strEndDate);
        pstmt.setString(4, subscriptionType);
        pstmt.setString(5, "unpaid"); // Initial payment status
        pstmt.executeUpdate();
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    payup up= new payup();
       up.setVisible(true);
       dispose();
    
    
    
    }//GEN-LAST:event_btnsubmitedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String username = "username"; 
                new plan(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmited;
    private javax.swing.JComboBox<String> combosub;
    private javax.swing.JLabel date2;
    private rojeru_san.componentes.RSDateChooser dates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
